package com.example.HiBuddy.domain.user;

public enum Major {
    // 공학계열
    MECHANICAL_ENGINEERING,
    NAVAL_ARCHITECTURE_OCEAN_ENGINEERING,
    AEROSPACE_ENGINEERING,
    INDUSTRIAL_ENGINEERING,
    ENVIRONMENTAL_ENGINEERING,
    POLYMER_SCIENCE_ENGINEERING,
    CIVIL_ENGINEERING,
    ARCHITECTURAL_ENGINEERING,
    GEOINFORMATIC_ENGINEERING,
    MATERIALS_SCIENCE_ENGINEERING,
    ENERGY_RESOURCES_ENGINEERING,
    SMART_CONSTRUCTION_MACHINERY_ENGINEERING,
    ELECTRICAL_COMPUTER_ENGINEERING,
    ARCHITECTURE,

    // 이학계열
    MATHEMATICS,
    PHYSICS,
    FOOD_AND_NUTRITION,
    NURSING,
    MATHEMATICS_EDUCATION,
    FASHION_DESIGN_TEXTILES,
    OCEAN_SCIENCES,

    // 인문사회계열
    ENGLISH_LANGUAGE_LITERATURE,
    JAPANESE_LANGUAGE_CULTURE,
    SINOLOGY,
    EDUCATION,
    DEPARTMENT_OF_FRANCOPHONE_STUDIES,
    BUSINESS_ADMINISTRATION,
    INTERNATIONAL_TRADE,
    ECONOMICS,
    ACCOUNTING,
    LAW,
    PUBLIC_ADMINISTRATION,
    POLITICAL_SCIENCE_INTERNATIONAL_RELATIONS,
    MEDIA_AND_COMMUNICATION,
    SOCIAL_STUDIES_EDUCATION,
    INTELLECTUAL_PROPERTY_LAW,
    CONSUMER_CHILD_STUDIES,
    KOREAN_LANGUAGE_EDUCATION,
    ENGLISH_LANGUAGE_EDUCATION,
    GLOBAL_BANKING_FINANCE,
    KOREAN_LANGUAGE_LITERATURE,
    HISTORY,
    MULTICULTURAL_EDUCATION,
    SOCIAL_WORK,

    // 예체능계열
    VISUAL_ARTS,
    DESIGN_CONVERGENCE,
    SPORTS_SCIENCE,
    HEALTH_EXERCISE_SCIENCE,
    DESIGN_TECHNOLOGY,

    // 의학계열
    MEDICINE,

    // 계열간 융합학과
    CHEMISTRY_CHEMICAL_ENGINEERING,
    BIOLOGICAL_SCIENCES_BIOENGINEERING,
    STATISTICS_DATA_SCIENCE,

    // 학과간 협동과정 (공학계열)
    ENVIRONMENTAL_POLYMER_ENGINEERING,
    CIRCULAR_ECONOMY_ENVIRONMENTAL_SYSTEM,
    METALS_MATERIALS_PROCESS_ENGINEERING,
    DIGITAL_ARTS_TECHNOLOGY,
    SMART_DIGITAL_ENGINEERING,
    SMART_CITY_ENGINEERING,
    ET_ST_CONVERGENCE,
    IT_MEDIA_CONVERGENCE_STUDIES,
    HUMAN_ARTS_TECHNOLOGY,

    // 학과간 협동과정 (자연과학계열)
    BIOMEDICAL_SCIENCE_ENGINEERING,

    // 학과간 협동과정 (인문사회계열)
    PHILOSOPHICAL_CULTURAL_STUDIES_OF_TECHNOLOGY,
    GREEN_FINANCE,
    MULTICULTURAL_STUDIES,
    URBAN_PLANNING,
    URBAN_REGENERATION,
    CULTURE_MANAGEMENT,
    INDUSTRIAL_SECURITY_GOVERNANCE,
    SERVICE_MANAGEMENT_ENGINEERING,
    INTEGRATIVE_HEALTH_SCIENCE,
    ARCHAEOLOGY_AS_INTERDISCIPLINARY_SCIENCE,
    HUMANITIES_THERAPY,
    INTERACTIVE_CONTENTS,
    SUSTAINABILITY_MANAGEMENT,
    FTA_POLICY_BUSINESS_CONSULTING,

    // 융합전공
    WHITE_BIO_CONVERGENCE_TECHNOLOGY,
    SPORTS_MEDICINE_CONVERGENCE,
    SEMICONDUCTOR_DEVICE_PROCESS,
    ENERGY_PROCESS_INNOVATION_CONVERGENCE,

    // 외국인 전담학과
    LAW_POLICY_ON_AI_DATA,
    GLOBAL_NURSING_SCIENCE,
    PROGRAM_IN_GLOBAL_EXERCISE_SCIENCE
}
